<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<NoWarn>0164;0162</NoWarn>
		<RootNamespace>Cryogenic.Harness</RootNamespace>
		<AssemblyName>Cryogenic.Harness</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Spice86" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Cryogenic\Cryogenic.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Spice86.Core.Emulator.Memory" />
		<Using Include="Spice86.Core.Emulator.ReverseEngineer" />
		<Using Include="Spice86.Core.Emulator.VM" />
		<Using Include="Spice86.Shared.Utils" />
	</ItemGroup>
</Project>
